server:
  port: 8083
spring:
  rabbitmq:
    host: 192.168.10.128
    #5672是rabbitMq的默认端口 15672是客户端管理界面端口
    port: 5672
    username: admin
    password: admin
  application:
    name: springcloudservice
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties:
        druid:
          stat:
            mergeSql: true
            slowSqlMillis : 5000
      useGlobalDataSourceStat: true
    url: jdbc:mysql://localhost:3306/1805?useUnicode=true&characterEncoding=utf8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml