server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
spring:
  application:
    name: springcloudweb
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
    #登录报错加这个
ribbon:
  eureka:
    enabled: true